# Site settings
title: dapplo .NET
email: info@dapplo.net
author:
 name: Robin Krom
 email: robin@dapplo.net
description: "dapplo - Desktop APP building bLOcks for .NET"
baseurl: ""
url: "http://www.dapplo.net"
twitter_username: dapplo_net
github_username: dapplo
facebook: dapplo
#googleplus: dapplo
openhub_project: dapplo
collections:
 blocks:
  output: true
 faqs:
  output: false

# Build settings
markdown: redcarpet
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME']

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
 input: GFM

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "hard_wrap"]

prose:
 metadata:
  _posts:
   - name: "title"
     field:
      element: "text"
      label: "Title"
   - name: layout
     field:
      element: "hidden"
      value: "blog"
   - name: categories
     field:
      element: "hidden"
      value: "blog"
  _blocks:
   - name: "title"
     field:
      element: "text"
      label: "Title"
   - name: "layout"
     field:
      element: "hidden"
      value: "block"
   - name: "sort_id"
     field:
      element: "number"
      label: "Sort value"
      type: "number"
      value: "1"
