# Site settings
title: dapplo .NET
email: info@dapplo.net
description: "dapplo .NET is an application for running & a framework for developing small .NET applications without the fuss."
baseurl: ""
url: "http://www.dapplo.net"
twitter_username: dapplo_net
github_username: dapplo
facebook: dapplo
#googleplus: dapplo
openhub_project: dapplo

# Build settings
markdown: redcarpet
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME']

gems:
  - jemoji

kramdown:
 input: GFM

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "hard_wrap"]
